process.chdir(require('path').resolve(__dirname, '..'));
const assert=require('assert');
const {estadoMt,conteoMt,agruparMt,eventosMesMt,celdasCalendarioMt,csvMt}=require('../web/js/mantenciones.js');
const {periodoMesMt}=require('../web/js/mantenciones.js');
assert.deepEqual(periodoMesMt('2028-02'),{inicio:'2028-02-01',fecha:'2028-02-29'});
assert.deepEqual(periodoMesMt('2026-12'),{inicio:'2026-12-01',fecha:'2026-12-31'});
assert.throws(()=>periodoMesMt('2026-07'));
assert.throws(()=>periodoMesMt('2026-13'));
const equipo=(patente,region,ceco,estado,fecha,operacion='OPERATIVO')=>({patente,region,ceco,estado_equipo:operacion,calculo:{estado,fecha_proyectada:fecha}});
const equipos=[equipo('A','R1','C1','Mantención Vencida','2026-09-01'),equipo('B','R1','C1','Próxima a vencer','2026-09-30'),equipo('C','R1','C2','Mantención Vigente','2026-10-01'),equipo('D','R2','C3','Mantención Vencida','2026-09-01','FUERA DE SERVICIO'),equipo('E','R2','C3','REVISAR',null)];
const standby=new Set(['FUERA DE SERVICIO']);
assert.equal(estadoMt(equipos[3],standby),'Mantención Vencida');
assert.equal(estadoMt(equipos[4],standby),'STAND BY');
assert.deepEqual(conteoMt(equipos,standby),{estados:[2,1,1,1],total:5,porcentaje:50});
assert.equal(conteoMt([equipos[4]],standby).porcentaje,null);
assert.equal(conteoMt([],standby).total,0);
const grupos=agruparMt(equipos,standby);assert.equal(grupos.length,2);assert.equal(grupos[0].cecos.length,2);
assert.equal(grupos.reduce((n,g)=>n+g.conteo.total,0),5);
assert.deepEqual(eventosMesMt(equipos,'2026-09').map(e=>e.patente),['A','B','D']);
assert.deepEqual(eventosMesMt(equipos,'2026-09','R1').map(e=>e.patente),['A','B']);
assert.equal(eventosMesMt(equipos,'2026-13').length,0);
assert.equal(eventosMesMt(equipos.filter(e=>e.region!=='R1'),'2026-09').length,1);
const sept=celdasCalendarioMt('2026-09');assert.equal(sept[0],null);assert.equal(sept[1],'2026-09-01');assert.equal(sept.filter(Boolean).length,30);assert.equal(sept.length%7,0);
assert.equal(celdasCalendarioMt('2028-02').filter(Boolean).length,29);
assert.equal(celdasCalendarioMt('2027-02').filter(Boolean).length,28);
assert(csvMt([['=FORMULA','texto "citado"',-2]]).includes("'=FORMULA"));
console.log('OK: exclusiones, clasificación sin doble conteo, porcentajes, meses, calendario y CSV.');
const {informeCalendarioMt}=require('../web/js/calendario_descarga.js');
const informe=informeCalendarioMt(equipos,'2026-09','R1','2026-09-01','2026-09-22');
assert(informe.includes('<td>A</td>'));assert(informe.includes('<td>B</td>'));
assert(!informe.includes('<td>C</td>'));assert(!informe.includes('<td>D</td>'));
assert.equal((informe.match(/<td class="programado">/g)||[]).length,2);
assert(!informe.includes('<script'));assert(!informe.includes('src='));
const sinEventos=informeCalendarioMt(equipos,'2026-12','R1','2026-09-01','2026-09-22');assert(sinEventos.includes('Sin mantenciones proyectadas'));
const malicioso=informeCalendarioMt([{...equipos[0],patente:'<img src=x onerror=alert(1)>'}],'2026-09','R1','2026-09-01','2026-09-22');assert(!malicioso.includes('<img'));assert(malicioso.includes('&lt;img'));
assert.throws(()=>informeCalendarioMt(equipos,'2026-09','','',''));
console.log('OK: informe autónomo con calendario, tabla, filtro por región/mes y texto escapado.');
