const km$=id=>document.getElementById(id);
let kmDatos=null,kmVisibles=[];
const kmFmt=n=>Number.isFinite(n)?n.toLocaleString('es-CL',{maximumFractionDigits:2}):'—';
const kmFecha=s=>s?s.split('-').reverse().join('-'):'—';
function kmCelda(fila,valor,tipo='td'){const td=document.createElement(tipo);td.textContent=valor;fila.append(td);return td;}
function kmSub(td,texto){const sub=document.createElement('div');sub.className='km-sub';sub.textContent=texto;td.append(sub);}
function kmColumnas(){return ['Patente / CeCo','Unidad',...kmDatos.semanas.map(s=>`Semana ${s.numero} · ${kmFecha(s.fecha)}`),'KM U HR UM','Fecha UM','Intervalo','Última lectura','Saldo','Próxima mantención','Status mantención','Uso diario','Fecha proyectada'];}
function renderKM(){
 if(!kmDatos)return;
 const buscar=km$('km-buscar').value.trim().toUpperCase(),estado=km$('km-estado').value,region=km$('km-region').value;
 kmVisibles=kmDatos.equipos.filter(e=>(e.patente+' '+e.ceco).toUpperCase().includes(buscar)&&(!estado||e.calculo.estado===estado)&&(!region||e.region===region));
 km$('km-cabecera').replaceChildren();const cab=document.createElement('tr');kmColumnas().forEach(t=>kmCelda(cab,t,'th'));km$('km-cabecera').append(cab);
 km$('km-detalle').replaceChildren();
 for(const e of kmVisibles){const c=e.calculo,tr=document.createElement('tr');const nombre=kmCelda(tr,''),boton=document.createElement('button');boton.className='km-patente-boton';boton.type='button';boton.textContent=e.patente;boton.onclick=()=>{km$('km-patente').value=e.patente;renderGraficos();km$('km-resumen-grafico').scrollIntoView({behavior:'smooth',block:'center'});};nombre.append(boton);kmSub(nombre,e.region+' / '+e.ceco);kmCelda(tr,e.unidad||'—');
  for(const l of e.lecturas){const td=kmCelda(tr,l?`${kmFmt(l.valor)} ${l.unidad||''}`:'—');if(l){kmSub(td,kmFecha(l.fecha_lectura));td.title=`Envío: ${kmFecha(l.fecha_envio)} · fila ${l.fila_excel} de PruebaForm${l.unidad_desde_maestro?' · unidad desde maestro':''}${l.fecha_desde_envio?' · fecha desde envío':''}`;if(l.unidad_desde_maestro||l.fecha_desde_envio)kmSub(td,[l.unidad_desde_maestro?'Unidad del maestro':'',l.fecha_desde_envio?'Fecha de envío':''].filter(Boolean).join(' · '));}}
  kmCelda(tr,kmFmt(e.ultima_mantencion));const um=kmCelda(tr,kmFecha(e.fecha_mantencion));kmSub(um,e.origen_mantencion||'Maestro');if(e.fila_mantencion)kmSub(um,`Fila ${e.fila_mantencion} · envío ${kmFecha(e.fecha_envio_mantencion)}`);if(e.certificado_mantencion){const texto=e.certificado_mantencion;try{const url=new URL(texto);if(!['https:','http:'].includes(url.protocol))throw new Error('Esquema no permitido');const a=document.createElement('a');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Ver certificado';um.append(a);}catch{kmSub(um,'Certificado: '+texto);}}else if(e.fila_mantencion)kmSub(um,'Sin certificado');kmCelda(tr,`${kmFmt(e.intervalo)} ${e.unidad_intervalo||''}`);
  const actual=kmCelda(tr,kmFmt(c.actual));kmSub(actual,c.semana_actual?`Semana ${c.semana_actual} · ${kmFecha(c.fecha_lectura)}`:'Sin reporte');
  kmCelda(tr,kmFmt(c.saldo));kmCelda(tr,kmFmt(c.proxima));const status=kmCelda(tr,''),indicador=document.createElement('span');indicador.className='semaforo '+c.clase;indicador.textContent=c.estado;status.append(indicador);if(c.motivo)kmSub(status,c.motivo);
  kmCelda(tr,c.ritmo_diario===null?'—':`${kmFmt(c.ritmo_diario)} ${e.unidad}/día`);const proyectada=kmCelda(tr,kmFecha(c.fecha_proyectada));kmSub(proyectada,c.fecha_proyectada?(c.saldo<=0?'Estimada · objetivo alcanzado':'Estimada'):c.motivo_proyeccion);km$('km-detalle').append(tr);
 }
 if(!kmVisibles.length){const tr=document.createElement('tr');kmCelda(tr,'No hay patentes para estos filtros.').colSpan=kmColumnas().length;km$('km-detalle').append(tr);}
 km$('km-total').textContent=kmVisibles.length;for(const [id,nombre] of [['vigentes','Mantención Vigente'],['proximas','Próxima a vencer'],['vencidas','Mantención Vencida'],['revisar','REVISAR']])km$('km-'+id).textContent=kmVisibles.filter(e=>e.calculo.estado===nombre).length;
 const previa=km$('km-patente').value;km$('km-patente').replaceChildren();kmVisibles.forEach(e=>km$('km-patente').add(new Option(`${e.patente} · ${e.ceco}`,e.patente)));if(kmVisibles.some(e=>e.patente===previa))km$('km-patente').value=previa;else{const ejemplo=kmVisibles.find(e=>e.calculo.fecha_proyectada)||kmVisibles.find(e=>e.lecturas.some(l=>l&&l.valor!==null));if(ejemplo)km$('km-patente').value=ejemplo.patente;}renderGraficos();
}
function svgElemento(tag,atributos={},texto){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(atributos))el.setAttribute(k,String(v));if(texto!==undefined)el.textContent=texto;return el;}
function dibujarGrafico(id,puntos,unidad,barras=false,objetivo=null){
 const cont=km$(id);cont.replaceChildren();const validos=puntos.filter(p=>Number.isFinite(p.valor));if(!validos.length){const p=document.createElement('p');p.className='nota';p.textContent='No hay datos suficientes para este gráfico.';cont.append(p);return;}
 const w=650,h=300,m={l:80,r:22,t:26,b:50},n=puntos.length;
 const valores=validos.map(p=>p.valor);if(Number.isFinite(objetivo))valores.push(objetivo);
 let min=barras?0:Math.min(...valores),max=Math.max(...valores);const pad=(max-min)*.12||Math.max(max*.02,1);min=barras?0:Math.max(0,min-pad);max+=pad;
 const x=i=>m.l+(i+(barras?.5:0))*(w-m.l-m.r)/Math.max(1,barras?n:n-1),y=v=>h-m.b-(v-min)/(max-min)*(h-m.t-m.b);
 const svg=svgElemento('svg',{viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':`${barras?'Consumo diario':'Lectura'} por semana, ${unidad}`});svg.append(svgElemento('title',{},`${barras?'Consumo diario':'Lecturas semanales'} en ${unidad}`));
 for(let i=0;i<=4;i++){const v=min+(max-min)*i/4,py=y(v);svg.append(svgElemento('line',{x1:m.l,y1:py,x2:w-m.r,y2:py,class:'km-rejilla'}));svg.append(svgElemento('text',{x:m.l-9,y:py+4,'text-anchor':'end',class:'km-eje'},kmFmt(v)));}
 svg.append(svgElemento('text',{x:m.l,y:16,class:'km-eje'},unidad));
 if(Number.isFinite(objetivo)){svg.append(svgElemento('line',{x1:m.l,y1:y(objetivo),x2:w-m.r,y2:y(objetivo),class:'km-objetivo'}));svg.append(svgElemento('text',{x:w-m.r,y:y(objetivo)-5,'text-anchor':'end',class:'km-eje'},'Próxima mantención'));}
 const paso=Math.max(1,Math.ceil(n/10));let previo=null;
 puntos.forEach((p,i)=>{const px=x(i);if(i%paso===0||i===n-1)svg.append(svgElemento('text',{x:px,y:h-23,'text-anchor':'middle',class:'km-eje'},'S'+p.semana));if(!Number.isFinite(p.valor)){previo=null;return;}const py=y(p.valor);if(barras){const ancho=Math.min(35,(w-m.l-m.r)/n*.6);const bar=svgElemento('rect',{x:px-ancho/2,y:py,width:ancho,height:y(0)-py,class:'km-barra'});bar.append(svgElemento('title',{},p.detalle));svg.append(bar);}else{if(previo)svg.append(svgElemento('line',{x1:previo.x,y1:previo.y,x2:px,y2:py,class:'km-linea'}));const punto=svgElemento('circle',{cx:px,cy:py,r:5,class:'km-punto'});punto.append(svgElemento('title',{},p.detalle));svg.append(punto);previo={x:px,y:py};}});
 cont.append(svg);
}
function renderGraficos(){
 const e=kmVisibles.find(e=>e.patente===km$('km-patente').value);if(!e){km$('km-resumen-grafico').textContent='Sin patentes seleccionadas.';km$('km-grafico-lecturas').replaceChildren();km$('km-grafico-ritmo').replaceChildren();return;}
 const c=e.calculo;km$('km-titulo-lecturas').textContent=`Lecturas semanales · ${e.unidad||'unidad sin definir'}`;km$('km-titulo-ritmo').textContent=`Consumo diario entre lecturas · ${e.unidad||'—'}/día`;
 km$('km-resumen-grafico').textContent=`${e.patente} · ${e.ceco} · ${c.estado} · Saldo: ${kmFmt(c.saldo)} ${e.unidad||''} · Fecha proyectada: ${kmFecha(c.fecha_proyectada)}${c.fecha_proyectada?' (estimada)':' · '+c.motivo_proyeccion}${c.motivo?' · '+c.motivo:''}`;
 const puntos=kmDatos.semanas.map((s,i)=>{const l=e.lecturas[i];return {semana:s.numero,valor:l&&l.unidad===e.unidad?l.valor:null,detalle:`Semana ${s.numero} (${kmFecha(s.fecha)}): ${l?kmFmt(l.valor):'sin reporte'} ${l?.unidad||''}`};});
 dibujarGrafico('km-grafico-lecturas',puntos,e.unidad||'—',false,c.proxima);
 const ritmo=kmDatos.semanas.map(s=>{const v=c.variaciones.find(v=>v.semana===s.numero);return {semana:s.numero,valor:v?.ritmo??null,detalle:v?`S${v.desde_semana} a S${v.semana}: ${kmFmt(v.incremento)} ${e.unidad} en ${v.dias} días · ${kmFmt(v.ritmo)} ${e.unidad}/día`:'Sin comparación'};});
 dibujarGrafico('km-grafico-ritmo',ritmo,`${e.unidad||'—'}/día`,true);
}
async function consultarKM(event){
 event?.preventDefault();km$('km-consultar').disabled=true;km$('km-exportar').disabled=true;km$('km-resultados').hidden=true;kmDatos=null;kmVisibles=[];km$('km-mensaje').textContent='Consultando maestro y lecturas semanales…';
 try{if(location.protocol==='file:')throw new Error('Abre el portal desde http://127.0.0.1:8765.');const consulta=new URLSearchParams({inicio:km$('km-inicio').value,fecha:km$('km-fecha').value});const respuesta=await fetch('/api/seguimiento-km-hr?'+consulta,{cache:'no-store'});if(respuesta.status===404)throw new Error('Reinicia Iniciar_Panel.bat para habilitar KM-HR.');const datos=await respuesta.json();if(!respuesta.ok)throw new Error(datos.error||'No se pudo consultar el Excel.');if(datos.version!==2||!Array.isArray(datos.semanas)||!Array.isArray(datos.equipos))throw new Error('El servidor usa el seguimiento anterior. Detén y vuelve a ejecutar Iniciar_Panel.bat.');kmDatos=datos;
 const previa=km$('km-region').value;km$('km-region').replaceChildren(new Option('Todas',''));[...new Set(datos.equipos.map(e=>e.region))].sort().forEach(r=>km$('km-region').add(new Option(r,r)));if([...km$('km-region').options].some(o=>o.value===previa))km$('km-region').value=previa;
 km$('km-periodo').textContent=`${datos.semanas.length} semanas · S1: ${kmFecha(datos.inicio)} · Última referencia: ${kmFecha(datos.semanas.at(-1).fecha)}. Se incluye el día siguiente de cada referencia.`;renderKM();km$('km-resultados').hidden=false;km$('km-exportar').disabled=false;km$('km-mensaje').textContent='Consulta completada. '+datos.advertencias.join(' ');km$('km-fuente').textContent=`Maestro: ${datos.maestro} · Lecturas: ${datos.fuente} / ${datos.hoja}`;
 }catch(error){km$('km-mensaje').textContent=error.message;kmDatos=null;}finally{km$('km-consultar').disabled=false;}
}
km$('km-exportar').onclick=()=>{if(!kmDatos)return;const rows=[['Patente','Región','CeCo','Unidad',...kmDatos.semanas.map(s=>`Semana ${s.numero} ${s.fecha}`),'KM U HR UM','Fecha UM','Intervalo','UN IN','Última lectura','Fecha lectura','Saldo','Próxima mantención','Status mantención','Motivo revisión','Uso diario','Fecha proyectada','Motivo sin proyección','Origen UM','Fila actualización','Envío actualización','Certificado UM']];kmVisibles.forEach(e=>{const c=e.calculo;rows.push([e.patente,e.region,e.ceco,e.unidad,...e.lecturas.map(l=>l?`${l.valor??''} ${l.unidad||''}`:''),e.ultima_mantencion,e.fecha_mantencion,e.intervalo,e.unidad_intervalo,c.actual,c.fecha_lectura,c.saldo,c.proxima,c.estado,c.motivo,c.ritmo_diario,c.fecha_proyectada,c.motivo_proyeccion,e.origen_mantencion,e.fila_mantencion,e.fecha_envio_mantencion,e.certificado_mantencion]);});const csv=rows.map(r=>r.map(v=>{let s=String(v??'');if(typeof v==='string'&&/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`Seguimiento_KM_HR_${kmDatos.fecha}.csv`;a.click();URL.revokeObjectURL(url);};
km$('km-buscar').oninput=renderKM;km$('km-estado').onchange=renderKM;km$('km-region').onchange=renderKM;km$('km-patente').onchange=renderGraficos;
const hoyKM=new Date();km$('km-fecha').value=`${hoyKM.getFullYear()}-${String(hoyKM.getMonth()+1).padStart(2,'0')}-${String(hoyKM.getDate()).padStart(2,'0')}`;
km$('km-form').onsubmit=consultarKM;consultarKM();
